/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyAccountRouteImport } from './routes/verify-account'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as ProfilePinRouteImport } from './routes/profile-pin'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AppChildrenLayoutRouteImport } from './routes/_app/children/_layout'
import { Route as AppAdultLayoutRouteImport } from './routes/_app/adult/_layout'
import { Route as AppChildrenLayoutIndexRouteImport } from './routes/_app/children/_layout/index'
import { Route as AppAdultRewardSuccessIndexRouteImport } from './routes/_app/adult/reward-success/index'
import { Route as AppChildrenSettingLayoutRouteImport } from './routes/_app/children/setting/_layout'
import { Route as AppAdultSettingLayoutRouteImport } from './routes/_app/adult/setting/_layout'
import { Route as AppAdultRewardSuccessLayoutRouteImport } from './routes/_app/adult/reward-success/_layout'
import { Route as AppChildrenSettingLayoutChangePinSuccessRouteImport } from './routes/_app/children/setting/_layout/change-pin-success'
import { Route as AppChildrenSettingLayoutChangePinRouteImport } from './routes/_app/children/setting/_layout/change-pin'
import { Route as AppAdultSettingLayoutInformationRouteImport } from './routes/_app/adult/setting/_layout/information'
import { Route as AppAdultSettingLayoutCreateProfileRouteImport } from './routes/_app/adult/setting/_layout/create-profile'
import { Route as AppAdultSettingLayoutChangePinSuccessRouteImport } from './routes/_app/adult/setting/_layout/change-pin-success'
import { Route as AppAdultSettingLayoutChangePinRouteImport } from './routes/_app/adult/setting/_layout/change-pin'
import { Route as AppAdultSettingLayoutChangePasswordSuccessRouteImport } from './routes/_app/adult/setting/_layout/change-password-success'
import { Route as AppAdultSettingLayoutChangePasswordRouteImport } from './routes/_app/adult/setting/_layout/change-password'

const CreateSuccessLazyRouteImport = createFileRoute('/create-success')()
const AppAdultLayoutIndexLazyRouteImport = createFileRoute(
  '/_app/adult/_layout/',
)()
const AppChildrenLayoutTreasuryLazyRouteImport = createFileRoute(
  '/_app/children/_layout/treasury',
)()
const AppChildrenLayoutSettingsLazyRouteImport = createFileRoute(
  '/_app/children/_layout/settings',
)()
const AppChildrenLayoutJourneyLazyRouteImport = createFileRoute(
  '/_app/children/_layout/journey',
)()
const AppChildrenLayoutCharacterLazyRouteImport = createFileRoute(
  '/_app/children/_layout/character',
)()
const AppAdultLayoutTargetLazyRouteImport = createFileRoute(
  '/_app/adult/_layout/target',
)()
const AppAdultLayoutSettingsLazyRouteImport = createFileRoute(
  '/_app/adult/_layout/settings',
)()
const AppAdultLayoutRewardLazyRouteImport = createFileRoute(
  '/_app/adult/_layout/reward',
)()
const AppAdultLayoutJourneyLazyRouteImport = createFileRoute(
  '/_app/adult/_layout/journey',
)()

const CreateSuccessLazyRoute = CreateSuccessLazyRouteImport.update({
  id: '/create-success',
  path: '/create-success',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/create-success.lazy').then((d) => d.Route),
)
const VerifyAccountRoute = VerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePinRoute = ProfilePinRouteImport.update({
  id: '/profile-pin',
  path: '/profile-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/_auth/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChildrenLayoutRoute = AppChildrenLayoutRouteImport.update({
  id: '/children/_layout',
  path: '/children',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdultLayoutRoute = AppAdultLayoutRouteImport.update({
  id: '/adult/_layout',
  path: '/adult',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdultLayoutIndexLazyRoute = AppAdultLayoutIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdultLayoutRoute,
} as any).lazy(() =>
  import('./routes/_app/adult/_layout/index.lazy').then((d) => d.Route),
)
const AppChildrenLayoutIndexRoute = AppChildrenLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChildrenLayoutRoute,
} as any)
const AppAdultRewardSuccessIndexRoute =
  AppAdultRewardSuccessIndexRouteImport.update({
    id: '/adult/reward-success/',
    path: '/adult/reward-success/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppChildrenLayoutTreasuryLazyRoute =
  AppChildrenLayoutTreasuryLazyRouteImport.update({
    id: '/treasury',
    path: '/treasury',
    getParentRoute: () => AppChildrenLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_app/children/_layout/treasury.lazy').then((d) => d.Route),
  )
const AppChildrenLayoutSettingsLazyRoute =
  AppChildrenLayoutSettingsLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppChildrenLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_app/children/_layout/settings.lazy').then((d) => d.Route),
  )
const AppChildrenLayoutJourneyLazyRoute =
  AppChildrenLayoutJourneyLazyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => AppChildrenLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_app/children/_layout/journey.lazy').then((d) => d.Route),
  )
const AppChildrenLayoutCharacterLazyRoute =
  AppChildrenLayoutCharacterLazyRouteImport.update({
    id: '/character',
    path: '/character',
    getParentRoute: () => AppChildrenLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_app/children/_layout/character.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAdultLayoutTargetLazyRoute =
  AppAdultLayoutTargetLazyRouteImport.update({
    id: '/target',
    path: '/target',
    getParentRoute: () => AppAdultLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_app/adult/_layout/target.lazy').then((d) => d.Route),
  )
const AppAdultLayoutSettingsLazyRoute =
  AppAdultLayoutSettingsLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAdultLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_app/adult/_layout/settings.lazy').then((d) => d.Route),
  )
const AppAdultLayoutRewardLazyRoute =
  AppAdultLayoutRewardLazyRouteImport.update({
    id: '/reward',
    path: '/reward',
    getParentRoute: () => AppAdultLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_app/adult/_layout/reward.lazy').then((d) => d.Route),
  )
const AppAdultLayoutJourneyLazyRoute =
  AppAdultLayoutJourneyLazyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => AppAdultLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_app/adult/_layout/journey.lazy').then((d) => d.Route),
  )
const AppChildrenSettingLayoutRoute =
  AppChildrenSettingLayoutRouteImport.update({
    id: '/children/setting/_layout',
    path: '/children/setting',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAdultSettingLayoutRoute = AppAdultSettingLayoutRouteImport.update({
  id: '/adult/setting/_layout',
  path: '/adult/setting',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdultRewardSuccessLayoutRoute =
  AppAdultRewardSuccessLayoutRouteImport.update({
    id: '/adult/reward-success/_layout',
    path: '/adult/reward-success',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppChildrenSettingLayoutChangePinSuccessRoute =
  AppChildrenSettingLayoutChangePinSuccessRouteImport.update({
    id: '/change-pin-success',
    path: '/change-pin-success',
    getParentRoute: () => AppChildrenSettingLayoutRoute,
  } as any)
const AppChildrenSettingLayoutChangePinRoute =
  AppChildrenSettingLayoutChangePinRouteImport.update({
    id: '/change-pin',
    path: '/change-pin',
    getParentRoute: () => AppChildrenSettingLayoutRoute,
  } as any)
const AppAdultSettingLayoutInformationRoute =
  AppAdultSettingLayoutInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => AppAdultSettingLayoutRoute,
  } as any)
const AppAdultSettingLayoutCreateProfileRoute =
  AppAdultSettingLayoutCreateProfileRouteImport.update({
    id: '/create-profile',
    path: '/create-profile',
    getParentRoute: () => AppAdultSettingLayoutRoute,
  } as any)
const AppAdultSettingLayoutChangePinSuccessRoute =
  AppAdultSettingLayoutChangePinSuccessRouteImport.update({
    id: '/change-pin-success',
    path: '/change-pin-success',
    getParentRoute: () => AppAdultSettingLayoutRoute,
  } as any)
const AppAdultSettingLayoutChangePinRoute =
  AppAdultSettingLayoutChangePinRouteImport.update({
    id: '/change-pin',
    path: '/change-pin',
    getParentRoute: () => AppAdultSettingLayoutRoute,
  } as any)
const AppAdultSettingLayoutChangePasswordSuccessRoute =
  AppAdultSettingLayoutChangePasswordSuccessRouteImport.update({
    id: '/change-password-success',
    path: '/change-password-success',
    getParentRoute: () => AppAdultSettingLayoutRoute,
  } as any)
const AppAdultSettingLayoutChangePasswordRoute =
  AppAdultSettingLayoutChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AppAdultSettingLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/profile-pin': typeof ProfilePinRoute
  '/profiles': typeof ProfilesRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/create-success': typeof CreateSuccessLazyRoute
  '/adult': typeof AppAdultLayoutRouteWithChildren
  '/children': typeof AppChildrenLayoutRouteWithChildren
  '/adult/reward-success': typeof AppAdultRewardSuccessLayoutRoute
  '/adult/setting': typeof AppAdultSettingLayoutRouteWithChildren
  '/children/setting': typeof AppChildrenSettingLayoutRouteWithChildren
  '/adult/journey': typeof AppAdultLayoutJourneyLazyRoute
  '/adult/reward': typeof AppAdultLayoutRewardLazyRoute
  '/adult/settings': typeof AppAdultLayoutSettingsLazyRoute
  '/adult/target': typeof AppAdultLayoutTargetLazyRoute
  '/children/character': typeof AppChildrenLayoutCharacterLazyRoute
  '/children/journey': typeof AppChildrenLayoutJourneyLazyRoute
  '/children/settings': typeof AppChildrenLayoutSettingsLazyRoute
  '/children/treasury': typeof AppChildrenLayoutTreasuryLazyRoute
  '/adult/reward-success/': typeof AppAdultRewardSuccessIndexRoute
  '/children/': typeof AppChildrenLayoutIndexRoute
  '/adult/': typeof AppAdultLayoutIndexLazyRoute
  '/adult/setting/change-password': typeof AppAdultSettingLayoutChangePasswordRoute
  '/adult/setting/change-password-success': typeof AppAdultSettingLayoutChangePasswordSuccessRoute
  '/adult/setting/change-pin': typeof AppAdultSettingLayoutChangePinRoute
  '/adult/setting/change-pin-success': typeof AppAdultSettingLayoutChangePinSuccessRoute
  '/adult/setting/create-profile': typeof AppAdultSettingLayoutCreateProfileRoute
  '/adult/setting/information': typeof AppAdultSettingLayoutInformationRoute
  '/children/setting/change-pin': typeof AppChildrenSettingLayoutChangePinRoute
  '/children/setting/change-pin-success': typeof AppChildrenSettingLayoutChangePinSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/profile-pin': typeof ProfilePinRoute
  '/profiles': typeof ProfilesRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/create-success': typeof CreateSuccessLazyRoute
  '/adult/reward-success': typeof AppAdultRewardSuccessIndexRoute
  '/adult/setting': typeof AppAdultSettingLayoutRouteWithChildren
  '/children/setting': typeof AppChildrenSettingLayoutRouteWithChildren
  '/adult/journey': typeof AppAdultLayoutJourneyLazyRoute
  '/adult/reward': typeof AppAdultLayoutRewardLazyRoute
  '/adult/settings': typeof AppAdultLayoutSettingsLazyRoute
  '/adult/target': typeof AppAdultLayoutTargetLazyRoute
  '/children/character': typeof AppChildrenLayoutCharacterLazyRoute
  '/children/journey': typeof AppChildrenLayoutJourneyLazyRoute
  '/children/settings': typeof AppChildrenLayoutSettingsLazyRoute
  '/children/treasury': typeof AppChildrenLayoutTreasuryLazyRoute
  '/children': typeof AppChildrenLayoutIndexRoute
  '/adult': typeof AppAdultLayoutIndexLazyRoute
  '/adult/setting/change-password': typeof AppAdultSettingLayoutChangePasswordRoute
  '/adult/setting/change-password-success': typeof AppAdultSettingLayoutChangePasswordSuccessRoute
  '/adult/setting/change-pin': typeof AppAdultSettingLayoutChangePinRoute
  '/adult/setting/change-pin-success': typeof AppAdultSettingLayoutChangePinSuccessRoute
  '/adult/setting/create-profile': typeof AppAdultSettingLayoutCreateProfileRoute
  '/adult/setting/information': typeof AppAdultSettingLayoutInformationRoute
  '/children/setting/change-pin': typeof AppChildrenSettingLayoutChangePinRoute
  '/children/setting/change-pin-success': typeof AppChildrenSettingLayoutChangePinSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/profile-pin': typeof ProfilePinRoute
  '/profiles': typeof ProfilesRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/create-success': typeof CreateSuccessLazyRoute
  '/_auth/': typeof AuthIndexRoute
  '/_app/adult/_layout': typeof AppAdultLayoutRouteWithChildren
  '/_app/children/_layout': typeof AppChildrenLayoutRouteWithChildren
  '/_app/adult/reward-success/_layout': typeof AppAdultRewardSuccessLayoutRoute
  '/_app/adult/setting/_layout': typeof AppAdultSettingLayoutRouteWithChildren
  '/_app/children/setting/_layout': typeof AppChildrenSettingLayoutRouteWithChildren
  '/_app/adult/_layout/journey': typeof AppAdultLayoutJourneyLazyRoute
  '/_app/adult/_layout/reward': typeof AppAdultLayoutRewardLazyRoute
  '/_app/adult/_layout/settings': typeof AppAdultLayoutSettingsLazyRoute
  '/_app/adult/_layout/target': typeof AppAdultLayoutTargetLazyRoute
  '/_app/children/_layout/character': typeof AppChildrenLayoutCharacterLazyRoute
  '/_app/children/_layout/journey': typeof AppChildrenLayoutJourneyLazyRoute
  '/_app/children/_layout/settings': typeof AppChildrenLayoutSettingsLazyRoute
  '/_app/children/_layout/treasury': typeof AppChildrenLayoutTreasuryLazyRoute
  '/_app/adult/reward-success/': typeof AppAdultRewardSuccessIndexRoute
  '/_app/children/_layout/': typeof AppChildrenLayoutIndexRoute
  '/_app/adult/_layout/': typeof AppAdultLayoutIndexLazyRoute
  '/_app/adult/setting/_layout/change-password': typeof AppAdultSettingLayoutChangePasswordRoute
  '/_app/adult/setting/_layout/change-password-success': typeof AppAdultSettingLayoutChangePasswordSuccessRoute
  '/_app/adult/setting/_layout/change-pin': typeof AppAdultSettingLayoutChangePinRoute
  '/_app/adult/setting/_layout/change-pin-success': typeof AppAdultSettingLayoutChangePinSuccessRoute
  '/_app/adult/setting/_layout/create-profile': typeof AppAdultSettingLayoutCreateProfileRoute
  '/_app/adult/setting/_layout/information': typeof AppAdultSettingLayoutInformationRoute
  '/_app/children/setting/_layout/change-pin': typeof AppChildrenSettingLayoutChangePinRoute
  '/_app/children/setting/_layout/change-pin-success': typeof AppChildrenSettingLayoutChangePinSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not-found'
    | '/profile-pin'
    | '/profiles'
    | '/register'
    | '/verify-account'
    | '/create-success'
    | '/adult'
    | '/children'
    | '/adult/reward-success'
    | '/adult/setting'
    | '/children/setting'
    | '/adult/journey'
    | '/adult/reward'
    | '/adult/settings'
    | '/adult/target'
    | '/children/character'
    | '/children/journey'
    | '/children/settings'
    | '/children/treasury'
    | '/adult/reward-success/'
    | '/children/'
    | '/adult/'
    | '/adult/setting/change-password'
    | '/adult/setting/change-password-success'
    | '/adult/setting/change-pin'
    | '/adult/setting/change-pin-success'
    | '/adult/setting/create-profile'
    | '/adult/setting/information'
    | '/children/setting/change-pin'
    | '/children/setting/change-pin-success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/not-found'
    | '/profile-pin'
    | '/profiles'
    | '/register'
    | '/verify-account'
    | '/create-success'
    | '/adult/reward-success'
    | '/adult/setting'
    | '/children/setting'
    | '/adult/journey'
    | '/adult/reward'
    | '/adult/settings'
    | '/adult/target'
    | '/children/character'
    | '/children/journey'
    | '/children/settings'
    | '/children/treasury'
    | '/children'
    | '/adult'
    | '/adult/setting/change-password'
    | '/adult/setting/change-password-success'
    | '/adult/setting/change-pin'
    | '/adult/setting/change-pin-success'
    | '/adult/setting/create-profile'
    | '/adult/setting/information'
    | '/children/setting/change-pin'
    | '/children/setting/change-pin-success'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/not-found'
    | '/profile-pin'
    | '/profiles'
    | '/register'
    | '/verify-account'
    | '/create-success'
    | '/_auth/'
    | '/_app/adult/_layout'
    | '/_app/children/_layout'
    | '/_app/adult/reward-success/_layout'
    | '/_app/adult/setting/_layout'
    | '/_app/children/setting/_layout'
    | '/_app/adult/_layout/journey'
    | '/_app/adult/_layout/reward'
    | '/_app/adult/_layout/settings'
    | '/_app/adult/_layout/target'
    | '/_app/children/_layout/character'
    | '/_app/children/_layout/journey'
    | '/_app/children/_layout/settings'
    | '/_app/children/_layout/treasury'
    | '/_app/adult/reward-success/'
    | '/_app/children/_layout/'
    | '/_app/adult/_layout/'
    | '/_app/adult/setting/_layout/change-password'
    | '/_app/adult/setting/_layout/change-password-success'
    | '/_app/adult/setting/_layout/change-pin'
    | '/_app/adult/setting/_layout/change-pin-success'
    | '/_app/adult/setting/_layout/create-profile'
    | '/_app/adult/setting/_layout/information'
    | '/_app/children/setting/_layout/change-pin'
    | '/_app/children/setting/_layout/change-pin-success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  ProfilePinRoute: typeof ProfilePinRoute
  ProfilesRoute: typeof ProfilesRoute
  RegisterRoute: typeof RegisterRoute
  VerifyAccountRoute: typeof VerifyAccountRoute
  CreateSuccessLazyRoute: typeof CreateSuccessLazyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-success': {
      id: '/create-success'
      path: '/create-success'
      fullPath: '/create-success'
      preLoaderRoute: typeof CreateSuccessLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-account': {
      id: '/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof VerifyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-pin': {
      id: '/profile-pin'
      path: '/profile-pin'
      fullPath: '/profile-pin'
      preLoaderRoute: typeof ProfilePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/children/_layout': {
      id: '/_app/children/_layout'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AppChildrenLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/adult/_layout': {
      id: '/_app/adult/_layout'
      path: '/adult'
      fullPath: '/adult'
      preLoaderRoute: typeof AppAdultLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/adult/_layout/': {
      id: '/_app/adult/_layout/'
      path: '/'
      fullPath: '/adult/'
      preLoaderRoute: typeof AppAdultLayoutIndexLazyRouteImport
      parentRoute: typeof AppAdultLayoutRoute
    }
    '/_app/children/_layout/': {
      id: '/_app/children/_layout/'
      path: '/'
      fullPath: '/children/'
      preLoaderRoute: typeof AppChildrenLayoutIndexRouteImport
      parentRoute: typeof AppChildrenLayoutRoute
    }
    '/_app/adult/reward-success/': {
      id: '/_app/adult/reward-success/'
      path: '/adult/reward-success'
      fullPath: '/adult/reward-success/'
      preLoaderRoute: typeof AppAdultRewardSuccessIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/children/_layout/treasury': {
      id: '/_app/children/_layout/treasury'
      path: '/treasury'
      fullPath: '/children/treasury'
      preLoaderRoute: typeof AppChildrenLayoutTreasuryLazyRouteImport
      parentRoute: typeof AppChildrenLayoutRoute
    }
    '/_app/children/_layout/settings': {
      id: '/_app/children/_layout/settings'
      path: '/settings'
      fullPath: '/children/settings'
      preLoaderRoute: typeof AppChildrenLayoutSettingsLazyRouteImport
      parentRoute: typeof AppChildrenLayoutRoute
    }
    '/_app/children/_layout/journey': {
      id: '/_app/children/_layout/journey'
      path: '/journey'
      fullPath: '/children/journey'
      preLoaderRoute: typeof AppChildrenLayoutJourneyLazyRouteImport
      parentRoute: typeof AppChildrenLayoutRoute
    }
    '/_app/children/_layout/character': {
      id: '/_app/children/_layout/character'
      path: '/character'
      fullPath: '/children/character'
      preLoaderRoute: typeof AppChildrenLayoutCharacterLazyRouteImport
      parentRoute: typeof AppChildrenLayoutRoute
    }
    '/_app/adult/_layout/target': {
      id: '/_app/adult/_layout/target'
      path: '/target'
      fullPath: '/adult/target'
      preLoaderRoute: typeof AppAdultLayoutTargetLazyRouteImport
      parentRoute: typeof AppAdultLayoutRoute
    }
    '/_app/adult/_layout/settings': {
      id: '/_app/adult/_layout/settings'
      path: '/settings'
      fullPath: '/adult/settings'
      preLoaderRoute: typeof AppAdultLayoutSettingsLazyRouteImport
      parentRoute: typeof AppAdultLayoutRoute
    }
    '/_app/adult/_layout/reward': {
      id: '/_app/adult/_layout/reward'
      path: '/reward'
      fullPath: '/adult/reward'
      preLoaderRoute: typeof AppAdultLayoutRewardLazyRouteImport
      parentRoute: typeof AppAdultLayoutRoute
    }
    '/_app/adult/_layout/journey': {
      id: '/_app/adult/_layout/journey'
      path: '/journey'
      fullPath: '/adult/journey'
      preLoaderRoute: typeof AppAdultLayoutJourneyLazyRouteImport
      parentRoute: typeof AppAdultLayoutRoute
    }
    '/_app/children/setting/_layout': {
      id: '/_app/children/setting/_layout'
      path: '/children/setting'
      fullPath: '/children/setting'
      preLoaderRoute: typeof AppChildrenSettingLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/adult/setting/_layout': {
      id: '/_app/adult/setting/_layout'
      path: '/adult/setting'
      fullPath: '/adult/setting'
      preLoaderRoute: typeof AppAdultSettingLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/adult/reward-success/_layout': {
      id: '/_app/adult/reward-success/_layout'
      path: '/adult/reward-success'
      fullPath: '/adult/reward-success'
      preLoaderRoute: typeof AppAdultRewardSuccessLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/children/setting/_layout/change-pin-success': {
      id: '/_app/children/setting/_layout/change-pin-success'
      path: '/change-pin-success'
      fullPath: '/children/setting/change-pin-success'
      preLoaderRoute: typeof AppChildrenSettingLayoutChangePinSuccessRouteImport
      parentRoute: typeof AppChildrenSettingLayoutRoute
    }
    '/_app/children/setting/_layout/change-pin': {
      id: '/_app/children/setting/_layout/change-pin'
      path: '/change-pin'
      fullPath: '/children/setting/change-pin'
      preLoaderRoute: typeof AppChildrenSettingLayoutChangePinRouteImport
      parentRoute: typeof AppChildrenSettingLayoutRoute
    }
    '/_app/adult/setting/_layout/information': {
      id: '/_app/adult/setting/_layout/information'
      path: '/information'
      fullPath: '/adult/setting/information'
      preLoaderRoute: typeof AppAdultSettingLayoutInformationRouteImport
      parentRoute: typeof AppAdultSettingLayoutRoute
    }
    '/_app/adult/setting/_layout/create-profile': {
      id: '/_app/adult/setting/_layout/create-profile'
      path: '/create-profile'
      fullPath: '/adult/setting/create-profile'
      preLoaderRoute: typeof AppAdultSettingLayoutCreateProfileRouteImport
      parentRoute: typeof AppAdultSettingLayoutRoute
    }
    '/_app/adult/setting/_layout/change-pin-success': {
      id: '/_app/adult/setting/_layout/change-pin-success'
      path: '/change-pin-success'
      fullPath: '/adult/setting/change-pin-success'
      preLoaderRoute: typeof AppAdultSettingLayoutChangePinSuccessRouteImport
      parentRoute: typeof AppAdultSettingLayoutRoute
    }
    '/_app/adult/setting/_layout/change-pin': {
      id: '/_app/adult/setting/_layout/change-pin'
      path: '/change-pin'
      fullPath: '/adult/setting/change-pin'
      preLoaderRoute: typeof AppAdultSettingLayoutChangePinRouteImport
      parentRoute: typeof AppAdultSettingLayoutRoute
    }
    '/_app/adult/setting/_layout/change-password-success': {
      id: '/_app/adult/setting/_layout/change-password-success'
      path: '/change-password-success'
      fullPath: '/adult/setting/change-password-success'
      preLoaderRoute: typeof AppAdultSettingLayoutChangePasswordSuccessRouteImport
      parentRoute: typeof AppAdultSettingLayoutRoute
    }
    '/_app/adult/setting/_layout/change-password': {
      id: '/_app/adult/setting/_layout/change-password'
      path: '/change-password'
      fullPath: '/adult/setting/change-password'
      preLoaderRoute: typeof AppAdultSettingLayoutChangePasswordRouteImport
      parentRoute: typeof AppAdultSettingLayoutRoute
    }
  }
}

interface AppAdultLayoutRouteChildren {
  AppAdultLayoutJourneyLazyRoute: typeof AppAdultLayoutJourneyLazyRoute
  AppAdultLayoutRewardLazyRoute: typeof AppAdultLayoutRewardLazyRoute
  AppAdultLayoutSettingsLazyRoute: typeof AppAdultLayoutSettingsLazyRoute
  AppAdultLayoutTargetLazyRoute: typeof AppAdultLayoutTargetLazyRoute
  AppAdultLayoutIndexLazyRoute: typeof AppAdultLayoutIndexLazyRoute
}

const AppAdultLayoutRouteChildren: AppAdultLayoutRouteChildren = {
  AppAdultLayoutJourneyLazyRoute: AppAdultLayoutJourneyLazyRoute,
  AppAdultLayoutRewardLazyRoute: AppAdultLayoutRewardLazyRoute,
  AppAdultLayoutSettingsLazyRoute: AppAdultLayoutSettingsLazyRoute,
  AppAdultLayoutTargetLazyRoute: AppAdultLayoutTargetLazyRoute,
  AppAdultLayoutIndexLazyRoute: AppAdultLayoutIndexLazyRoute,
}

const AppAdultLayoutRouteWithChildren = AppAdultLayoutRoute._addFileChildren(
  AppAdultLayoutRouteChildren,
)

interface AppChildrenLayoutRouteChildren {
  AppChildrenLayoutCharacterLazyRoute: typeof AppChildrenLayoutCharacterLazyRoute
  AppChildrenLayoutJourneyLazyRoute: typeof AppChildrenLayoutJourneyLazyRoute
  AppChildrenLayoutSettingsLazyRoute: typeof AppChildrenLayoutSettingsLazyRoute
  AppChildrenLayoutTreasuryLazyRoute: typeof AppChildrenLayoutTreasuryLazyRoute
  AppChildrenLayoutIndexRoute: typeof AppChildrenLayoutIndexRoute
}

const AppChildrenLayoutRouteChildren: AppChildrenLayoutRouteChildren = {
  AppChildrenLayoutCharacterLazyRoute: AppChildrenLayoutCharacterLazyRoute,
  AppChildrenLayoutJourneyLazyRoute: AppChildrenLayoutJourneyLazyRoute,
  AppChildrenLayoutSettingsLazyRoute: AppChildrenLayoutSettingsLazyRoute,
  AppChildrenLayoutTreasuryLazyRoute: AppChildrenLayoutTreasuryLazyRoute,
  AppChildrenLayoutIndexRoute: AppChildrenLayoutIndexRoute,
}

const AppChildrenLayoutRouteWithChildren =
  AppChildrenLayoutRoute._addFileChildren(AppChildrenLayoutRouteChildren)

interface AppAdultSettingLayoutRouteChildren {
  AppAdultSettingLayoutChangePasswordRoute: typeof AppAdultSettingLayoutChangePasswordRoute
  AppAdultSettingLayoutChangePasswordSuccessRoute: typeof AppAdultSettingLayoutChangePasswordSuccessRoute
  AppAdultSettingLayoutChangePinRoute: typeof AppAdultSettingLayoutChangePinRoute
  AppAdultSettingLayoutChangePinSuccessRoute: typeof AppAdultSettingLayoutChangePinSuccessRoute
  AppAdultSettingLayoutCreateProfileRoute: typeof AppAdultSettingLayoutCreateProfileRoute
  AppAdultSettingLayoutInformationRoute: typeof AppAdultSettingLayoutInformationRoute
}

const AppAdultSettingLayoutRouteChildren: AppAdultSettingLayoutRouteChildren = {
  AppAdultSettingLayoutChangePasswordRoute:
    AppAdultSettingLayoutChangePasswordRoute,
  AppAdultSettingLayoutChangePasswordSuccessRoute:
    AppAdultSettingLayoutChangePasswordSuccessRoute,
  AppAdultSettingLayoutChangePinRoute: AppAdultSettingLayoutChangePinRoute,
  AppAdultSettingLayoutChangePinSuccessRoute:
    AppAdultSettingLayoutChangePinSuccessRoute,
  AppAdultSettingLayoutCreateProfileRoute:
    AppAdultSettingLayoutCreateProfileRoute,
  AppAdultSettingLayoutInformationRoute: AppAdultSettingLayoutInformationRoute,
}

const AppAdultSettingLayoutRouteWithChildren =
  AppAdultSettingLayoutRoute._addFileChildren(
    AppAdultSettingLayoutRouteChildren,
  )

interface AppChildrenSettingLayoutRouteChildren {
  AppChildrenSettingLayoutChangePinRoute: typeof AppChildrenSettingLayoutChangePinRoute
  AppChildrenSettingLayoutChangePinSuccessRoute: typeof AppChildrenSettingLayoutChangePinSuccessRoute
}

const AppChildrenSettingLayoutRouteChildren: AppChildrenSettingLayoutRouteChildren =
  {
    AppChildrenSettingLayoutChangePinRoute:
      AppChildrenSettingLayoutChangePinRoute,
    AppChildrenSettingLayoutChangePinSuccessRoute:
      AppChildrenSettingLayoutChangePinSuccessRoute,
  }

const AppChildrenSettingLayoutRouteWithChildren =
  AppChildrenSettingLayoutRoute._addFileChildren(
    AppChildrenSettingLayoutRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAdultLayoutRoute: typeof AppAdultLayoutRouteWithChildren
  AppChildrenLayoutRoute: typeof AppChildrenLayoutRouteWithChildren
  AppAdultRewardSuccessLayoutRoute: typeof AppAdultRewardSuccessLayoutRoute
  AppAdultSettingLayoutRoute: typeof AppAdultSettingLayoutRouteWithChildren
  AppChildrenSettingLayoutRoute: typeof AppChildrenSettingLayoutRouteWithChildren
  AppAdultRewardSuccessIndexRoute: typeof AppAdultRewardSuccessIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdultLayoutRoute: AppAdultLayoutRouteWithChildren,
  AppChildrenLayoutRoute: AppChildrenLayoutRouteWithChildren,
  AppAdultRewardSuccessLayoutRoute: AppAdultRewardSuccessLayoutRoute,
  AppAdultSettingLayoutRoute: AppAdultSettingLayoutRouteWithChildren,
  AppChildrenSettingLayoutRoute: AppChildrenSettingLayoutRouteWithChildren,
  AppAdultRewardSuccessIndexRoute: AppAdultRewardSuccessIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  ProfilePinRoute: ProfilePinRoute,
  ProfilesRoute: ProfilesRoute,
  RegisterRoute: RegisterRoute,
  VerifyAccountRoute: VerifyAccountRoute,
  CreateSuccessLazyRoute: CreateSuccessLazyRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
