/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyAccountRouteImport } from './routes/verify-account'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'

const AppChildrenRouteLazyRouteImport = createFileRoute('/_app/children')()
const AppChildrenIndexLazyRouteImport = createFileRoute('/_app/children/')()

const VerifyAccountRoute = VerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChildrenRouteLazyRoute = AppChildrenRouteLazyRouteImport.update({
  id: '/_app/children',
  path: '/children',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_app/children/route.lazy').then((d) => d.Route),
)
const AppChildrenIndexLazyRoute = AppChildrenIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChildrenRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/_app/children/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AuthRouteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/children': typeof AppChildrenRouteLazyRouteWithChildren
  '/children/': typeof AppChildrenIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthRouteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/children': typeof AppChildrenIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/_app/children': typeof AppChildrenRouteLazyRouteWithChildren
  '/_app/children/': typeof AppChildrenIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/verify-account'
    | '/children'
    | '/children/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/verify-account' | '/children'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/verify-account'
    | '/_app/children'
    | '/_app/children/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyAccountRoute: typeof VerifyAccountRoute
  AppChildrenRouteLazyRoute: typeof AppChildrenRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-account': {
      id: '/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof VerifyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/children': {
      id: '/_app/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AppChildrenRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/children/': {
      id: '/_app/children/'
      path: '/'
      fullPath: '/children/'
      preLoaderRoute: typeof AppChildrenIndexLazyRouteImport
      parentRoute: typeof AppChildrenRouteLazyRoute
    }
  }
}

interface AppChildrenRouteLazyRouteChildren {
  AppChildrenIndexLazyRoute: typeof AppChildrenIndexLazyRoute
}

const AppChildrenRouteLazyRouteChildren: AppChildrenRouteLazyRouteChildren = {
  AppChildrenIndexLazyRoute: AppChildrenIndexLazyRoute,
}

const AppChildrenRouteLazyRouteWithChildren =
  AppChildrenRouteLazyRoute._addFileChildren(AppChildrenRouteLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyAccountRoute: VerifyAccountRoute,
  AppChildrenRouteLazyRoute: AppChildrenRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
